### ISSUE TITLE
Move repo to BC Gov

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-api#6]
@amanji and @WadeBarnes -- can the two of you coordinate on getting this repo moved into BCGov organization?  I'd like to enable updates to it by others.  It's ready!

**Comment by swcurran** [comment]
@WadeBarnes -- @amanji is on Hyperledger Rocketchat, although we should probably get him an account on the BC Dev Exchange Rocketchat.

**Comment by WadeBarnes** [comment]
Coordinating via RC

**Comment by WadeBarnes** [comment]
@swcurran, @amanji, Transfer complete, updating some project settings.

**Comment by WadeBarnes** [comment]
Transfer complete
